#                                        
format = """
[╭](#f92672)\
$python\
$username\
[](bg:#a6e22e fg:#f92672)\
$directory\
[](fg:#a6e22e bg:#66d9ef)\
$git_branch\
$git_status\
[](fg:#66d9ef bg:#fd971f00)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#ae81ff bg:#ae81ff)\
$docker_context\
[](bold italic fg:#ae81ff bg:#33658A)\
[](#33658A)\
$fill\
$fill\
$fill\
$fill\
$fill\
$fill\
$cmd_duration\
$character\
$fill\
$fill\
$fill\
$fill\
$fill\
$fill\
[](#f92672)\
$time\
[\n│](fg:#f92672)\
[\n╰────  ](fg:#f92672)\
"""



command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false
[fill]
symbol = ' '
style = 'bold green'

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#f92672"
style_root = "bg:#f92672"
format = '[   ]($style)'

[directory]
style = "bg:#a6e22e fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#fd971f00 fg:#0000ff"
format = '[ $symbol ($version) ]($style)'
detect_folders = ['Vendor' , 'vendor']
detect_extensions = ['c', 'h' , 'hpp' , 'cpp']


[docker_context]
symbol = " "
style = "bg:#ae81ff"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#66d9ef fg:#3b3b3b"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#66d9ef fg:#3b3b3b"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "Ⲗ "
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#fd971f00"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#f92672"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#fd971f00 fg:#ff0000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#f92672"
format = '[$time ⏲ ]($style)'


[cmd_duration]
min_time = 5000
show_notifications = true
style = "fg:blue bg:000000"
format = "[TOOK $duration ⏲ ]($style)"



[character]

success_symbol = "[ ❨succeeded❩](bold italic green)"
error_symbol = "[ ❨failed❩](bold italic red)"

